global:
  scrape_interval: 1m
  scrape_timeout: 30s
# rule_files:
#   - /etc/config/rules
#   - /etc/config/alerts
scrape_configs:
  - job_name: node
    static_configs:
      - targets:
        - host.docker.internal:9182
